name: seu_app_nome
description: Uma breve descrição do seu aplicativo

# Versão do seu aplicativo
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0" # Ajuste a versão do SDK conforme necessário

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0 # Versão mais recente do firebase_core
  cloud_firestore: ^4.0.0 # Versão mais recente do cloud_firestore
  intl: ^0.17.0 # Para formatação de moeda

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
